ALTER TABLE "secrets" ADD COLUMN "refresh_locked_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "secrets" ADD COLUMN "rotation_started_at" timestamp with time zone;--> statement-breakpoint
-- Backfill (not generated by drizzle-kit): the 60-minute refresh lock moved off
-- last_refreshed_at onto refresh_locked_at for the two agent-backend OAuth
-- purposes. Seeding the new column from the old one preserves the lock state that
-- is in force at deploy time — without it every credential would look unlocked and
-- the first cycle after the deploy could stack concurrent refreshes on a provider
-- that rotates the refresh token on every use.
-- Idempotent: only fills rows where the new column is still NULL.
UPDATE "secrets"
   SET "refresh_locked_at" = "last_refreshed_at"
 WHERE "refresh_locked_at" IS NULL
   AND "last_refreshed_at" IS NOT NULL
   AND "purpose" IN ('claude_credential', 'codex_credential');
