/**
 * Path prefixes of files generated by tooling that should be excluded from
 * line-count signals. This is the single source of truth — import here rather
 * than defining per-call-site patterns.
 *
 * NOTE: do NOT mark migration .sql files here — those are the reviewable
 * artifact and must keep triggering human-review gates.
 */
export const GENERATED_PATH_PREFIXES: readonly string[] = [
  'packages/core/drizzle/meta/', // Drizzle ORM snapshot JSON (_journal.json + *_snapshot.json)
];

export function isGeneratedPath(filename: string): boolean {
  return GENERATED_PATH_PREFIXES.some((prefix) => filename.startsWith(prefix));
}
