/**
 * apps/web/next-env.d.ts is generated by Next and rewritten by every local
 * run: `next dev` writes `.next/dev/types/...`, `next build` writes
 * `.next/types/...`. Agents kept committing the build variant after a local
 * build, which is churn and breaks dev typechecking. This pins the committed
 * blob (git HEAD, not the working tree, so a local build doesn't fail this
 * test) to the canonical `next dev` content. .githooks/pre-commit refuses to
 * stage the file at all.
 *
 * A deliberate change (a Next upgrade that changes the template): update
 * CANONICAL_NEXT_ENV below in the same commit, with `git commit --no-verify`.
 */
import { describe, expect, test } from 'bun:test';
import { execFileSync } from 'child_process';
import { join } from 'path';

const ROOT = join(import.meta.dir, '..');
const PATH = 'apps/web/next-env.d.ts';

export const CANONICAL_NEXT_ENV = `/// <reference types="next" />
/// <reference types="next/image-types/global" />
import "./.next/dev/types/routes.d.ts";
import "./.next/dev/types/root-params.d.ts";

// NOTE: This file should not be edited
// see https://nextjs.org/docs/app/api-reference/config/typescript for more information.
`;

function committed(): string {
  return execFileSync('git', ['show', `HEAD:${PATH}`], { cwd: ROOT, encoding: 'utf8' });
}

describe('apps/web/next-env.d.ts', () => {
  test('the committed file is the canonical next-dev content', () => {
    expect(committed()).toBe(CANONICAL_NEXT_ENV);
  });

  test('the next-build variant is not canonical (the guard can fail)', () => {
    const buildVariant = CANONICAL_NEXT_ENV.replaceAll('.next/dev/types/', '.next/types/');
    expect(buildVariant).not.toBe(CANONICAL_NEXT_ENV);
  });

  test('pre-commit refuses to stage it', async () => {
    const hook = await Bun.file(join(ROOT, '.githooks/pre-commit')).text();
    expect(hook).toContain(`git diff --cached --quiet -- ${PATH}`);
  });
});
