#!/usr/bin/env bash
# Create a release PR from dev → main with auto-detected semver.
# Uses conventional commits to determine bump: feat → minor, fix → patch, BREAKING CHANGE → major.
# Tags main with the version after merge.

set -euo pipefail

# Post-release cleanup: delete branches already in main
if [ "${1:-}" = "--cleanup" ]; then
  echo "🧹 Cleaning up stale branches..."
  git fetch origin --prune

  DELETED=0
  for branch in $(git branch -r --no-merged origin/main | grep 'origin/' | grep -v 'origin/main$' | grep -v 'origin/dev$' | grep -v 'origin/HEAD' | sed 's|origin/||'); do
    # Check if all commits in this branch are already in main (squash-merged)
    NEW_COMMITS=0
    for commit in $(git log origin/main..origin/$branch --format=%H --no-merges 2>/dev/null); do
      msg=$(git log -1 --format=%s "$commit" | cut -c1-40)
      if ! git log origin/main --oneline --grep="$msg" --fixed-strings 2>/dev/null | grep -q .; then
        NEW_COMMITS=$((NEW_COMMITS + 1))
      fi
    done

    if [ "$NEW_COMMITS" -eq 0 ]; then
      echo "  ✅ Deleting $branch (all changes in main)"
      git push origin --delete "$branch" 2>/dev/null || true
      DELETED=$((DELETED + 1))
    else
      echo "  ⏭️  Keeping $branch ($NEW_COMMITS unmerged commits)"
    fi
  done

  echo ""
  echo "🧹 Deleted $DELETED stale branches"
  exit 0
fi

# Get the latest version tag, default to v0.0.0
LATEST_TAG=$(git tag --sort=-v:refname --list 'v*' | head -1)
if [ -z "$LATEST_TAG" ]; then
  LATEST_TAG="v0.0.0"
fi

# Parse current version
VERSION="${LATEST_TAG#v}"
IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

# Determine bump from commits since last tag
if [ "$LATEST_TAG" = "v0.0.0" ]; then
  COMMITS=$(git log origin/main..dev --format='%s' --no-merges 2>/dev/null || git log --format='%s' --no-merges -50)
else
  COMMITS=$(git log "${LATEST_TAG}..dev" --format='%s' --no-merges 2>/dev/null || echo "")
fi

BUMP="patch"
while IFS= read -r msg; do
  [ -z "$msg" ] && continue
  if echo "$msg" | grep -qiE 'BREAKING[ -]CHANGE|^[a-z]+!:'; then
    BUMP="major"
    break
  elif echo "$msg" | grep -qE '^feat(\(.+\))?:'; then
    BUMP="minor"
  fi
done <<< "$COMMITS"

# Apply bump
case "$BUMP" in
  major) MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0 ;;
  minor) MINOR=$((MINOR + 1)); PATCH=0 ;;
  patch) PATCH=$((PATCH + 1)) ;;
esac

NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"

echo "Current: ${LATEST_TAG} → New: ${NEW_VERSION} (${BUMP} bump)"

# Build PR body with commit summary
BODY=$(cat <<EOF
## ${NEW_VERSION}

### Changes
$(git log origin/main..dev --format='- %s' --no-merges 2>/dev/null | head -30)

---
*Auto-generated by \`bun run release\`*
EOF
)

# Create or update PR
EXISTING_PR=$(gh pr list --base main --head dev --json number --jq '.[0].number' 2>/dev/null || echo "")

REPO=$(gh repo view --json nameWithOwner --jq '.nameWithOwner')

if [ -n "$EXISTING_PR" ]; then
  gh api "repos/${REPO}/pulls/${EXISTING_PR}" --method PATCH \
    -f title="Release ${NEW_VERSION}" -f body="$BODY" --silent
  echo "Updated PR #${EXISTING_PR}: Release ${NEW_VERSION}"
  echo "https://github.com/${REPO}/pull/${EXISTING_PR}"
else
  gh pr create --base main --head dev --title "Release ${NEW_VERSION}" --body "$BODY"
fi
