import { describe, it, expect } from 'bun:test';
import { ARTIFACT_TYPES } from '@buildd/shared';
import {
  BYPRODUCT_ARTIFACT_TYPES,
  REVIEW_ARTIFACT_TYPES,
  WORKING_ARTIFACT_TYPES,
  isReviewArtifact,
  partitionByReview,
} from './artifact-prominence';

/**
 * The prominence predicate is the ONLY place that decides whether an artifact
 * belongs in a human's review queue. These tests pin the boundary cases,
 * because every one of them is a real row shape this system writes today.
 */

describe('artifact type vocabulary partition', () => {
  it('classifies every type in ARTIFACT_TYPES exactly once', () => {
    const buckets = [
      ...REVIEW_ARTIFACT_TYPES,
      ...WORKING_ARTIFACT_TYPES,
      ...BYPRODUCT_ARTIFACT_TYPES,
    ];
    // No duplicates across buckets.
    expect(new Set(buckets).size).toBe(buckets.length);
    // Total coverage: adding a type to the shared vocabulary must force a
    // deliberate prominence decision rather than silently defaulting.
    expect([...buckets].sort()).toEqual([...ARTIFACT_TYPES].sort());
  });
});

describe('isReviewArtifact — review-shaped types', () => {
  it('promotes an unkeyed, container-less report (the plain create_artifact call)', () => {
    // Nothing in the platform auto-writes a `report` without a key, so an
    // unkeyed report is an agent that chose to write one. `key` is a strong
    // signal but must NOT be a requirement, or this hides the common case.
    expect(isReviewArtifact({ type: 'report' })).toBe(true);
  });

  it.each(['analysis', 'recommendation', 'walkthrough', 'summary', 'content', 'alert'])(
    'promotes %s on type alone',
    (type) => {
      expect(isReviewArtifact({ type })).toBe(true);
    },
  );

  it('promotes the auto-generated mission rollup (keyed report, autoGenerated metadata)', () => {
    // These are upserted one-per-mission by PATCH /api/workers/[id]. They are
    // machine-written but are precisely the digest a human reviews, and the
    // unique (workspaceId, key) index caps them at one row per mission — so
    // `metadata.autoGenerated` is deliberately NOT a disqualifier.
    expect(
      isReviewArtifact({
        type: 'report',
        key: 'mission-abc',
        missionId: 'm1',
        metadata: { autoGenerated: true },
      }),
    ).toBe(true);
  });
});

describe('isReviewArtifact — byproduct types stay out, even when keyed', () => {
  it.each(['screenshot', 'recording', 'diff', 'file', 'data', 'link', 'calendar_event'])(
    'excludes %s',
    (type) => {
      expect(isReviewArtifact({ type })).toBe(false);
    },
  );

  it('excludes a keyed byproduct — a key on a capture is an address, not intent', () => {
    // The spec-conformance CI marker is a keyed workspace-level `data` row
    // written by a machine credential on every run. Keying it makes it
    // upsertable; it is not a thing anyone reviews.
    expect(isReviewArtifact({ type: 'data', key: 'spec-conformance-last-sha' })).toBe(false);
  });

  it('excludes a mission-scoped screenshot', () => {
    expect(isReviewArtifact({ type: 'screenshot', missionId: 'm1' })).toBe(false);
  });
});

describe('isReviewArtifact — working artifacts (impl_plan)', () => {
  it('excludes a plain worker-level impl_plan', () => {
    // Every planning worker emits one. This preserves the exclusion the
    // artifacts page already had, instead of flooding the review view.
    expect(isReviewArtifact({ type: 'impl_plan' })).toBe(false);
  });

  it('promotes a keyed impl_plan — a named, upsertable plan is a document', () => {
    expect(isReviewArtifact({ type: 'impl_plan', key: 'roadmap-q3' })).toBe(true);
  });

  it('promotes a mission-level impl_plan', () => {
    expect(isReviewArtifact({ type: 'impl_plan', missionId: 'm1' })).toBe(true);
  });

  it('promotes an initiative-level impl_plan (the roadmap/spec case)', () => {
    expect(isReviewArtifact({ type: 'impl_plan', initiativeId: 'i1' })).toBe(true);
  });
});

describe('isReviewArtifact — visibility', () => {
  it('promotes anything explicitly shared, including a byproduct', () => {
    // `visibility: 'public'` is only ever set by an explicit Share action,
    // which also mints a bearer token. That is an unambiguous human decision.
    expect(isReviewArtifact({ type: 'screenshot', visibility: 'public' })).toBe(true);
  });

  it('does not promote a private byproduct that merely has a stale share token', () => {
    expect(isReviewArtifact({ type: 'diff', visibility: 'private' })).toBe(false);
  });
});

describe('isReviewArtifact — types outside the vocabulary', () => {
  it('requires a key or a container for an unknown type (the column is free text)', () => {
    expect(isReviewArtifact({ type: 'weird_new_thing' })).toBe(false);
    expect(isReviewArtifact({ type: 'weird_new_thing', key: 'named-thing' })).toBe(true);
    expect(isReviewArtifact({ type: 'weird_new_thing', initiativeId: 'i1' })).toBe(true);
  });

  it('treats an empty-string key as absent', () => {
    expect(isReviewArtifact({ type: 'impl_plan', key: '' })).toBe(false);
  });
});

describe('partitionByReview', () => {
  it('splits a mixed list, preserving input order within each group', () => {
    const rows = [
      { type: 'report', title: 'a' },
      { type: 'screenshot', title: 'b' },
      { type: 'analysis', title: 'c' },
      { type: 'impl_plan', title: 'd' },
    ];
    const { review, incidental } = partitionByReview(rows);
    expect(review.map((r) => r.title)).toEqual(['a', 'c']);
    expect(incidental.map((r) => r.title)).toEqual(['b', 'd']);
  });
});
