import { describe, it, expect, beforeEach, mock } from 'bun:test';

const mockArtifactsFindFirst = mock(() => null as any);
const mockArtifactsInsert = mock(() => ({
  values: mock(() => ({
    returning: mock(() => [{ id: 'artifact-1', shareToken: 'test-share-token' }]),
  })),
}));
const mockArtifactsUpdate = mock(() => ({
  set: mock(() => ({
    where: mock(() => ({
      returning: mock(() => [{ id: 'artifact-1', shareToken: 'existing-share-token' }]),
    })),
  })),
}));
const mockTriggerEvent = mock(() => Promise.resolve());

mock.module('@buildd/core/db', () => ({
  db: {
    query: {
      artifacts: { findFirst: mockArtifactsFindFirst },
    },
    insert: () => mockArtifactsInsert(),
    update: () => mockArtifactsUpdate(),
  },
}));

mock.module('drizzle-orm', () => ({
  eq: (field: any, value: any) => ({ field, value, type: 'eq' }),
  and: (...conditions: any[]) => ({ conditions, type: 'and' }),
}));

mock.module('@buildd/core/db/schema', () => ({
  artifacts: 'artifacts',
}));

mock.module('@/lib/pusher', () => ({
  triggerEvent: mockTriggerEvent,
  channels: {
    worker: (id: string) => `worker-${id}`,
    workspace: (id: string) => `workspace-${id}`,
  },
  events: {
    WORKER_PROGRESS: 'worker:progress',
  },
}));

mock.module('crypto', () => ({
  randomBytes: () => ({ toString: () => 'generated-share-token' }),
}));

import {
  generateShareToken,
  formatStructuredOutput,
  upsertAutoArtifact,
} from './artifact-helpers';

describe('generateShareToken', () => {
  it('returns a string token', () => {
    const token = generateShareToken();
    expect(typeof token).toBe('string');
    expect(token.length).toBeGreaterThan(0);
  });
});

describe('formatStructuredOutput', () => {
  it('formats heartbeat output as markdown', () => {
    const output = {
      status: 'ok',
      summary: 'All systems running normally',
      checksPerformed: ['CI pipeline status', 'Error rate check'],
      actionsPerformed: [],
    };
    const result = formatStructuredOutput(output, 'Task summary here');

    expect(result).toContain('## Status: ok');
    expect(result).toContain('All systems running normally');
    expect(result).toContain('CI pipeline status');
    expect(result).toContain('Error rate check');
  });

  it('formats heartbeat with actions performed', () => {
    const output = {
      status: 'action_taken',
      summary: 'Restarted staging',
      checksPerformed: ['Server health'],
      actionsPerformed: ['Restarted staging server'],
    };
    const result = formatStructuredOutput(output);

    expect(result).toContain('## Status: action_taken');
    expect(result).toContain('Restarted staging server');
  });

  it('renders generic structured output as key-value pairs', () => {
    const output = {
      recommendation: 'Use option B',
      reasoning: 'Better performance',
    };
    const result = formatStructuredOutput(output);

    expect(result).toContain('recommendation');
    expect(result).toContain('Use option B');
  });

  it('uses summary fallback when no structuredOutput', () => {
    const result = formatStructuredOutput(undefined, 'Just a summary');
    expect(result).toBe('Just a summary');
  });

  it('returns empty string when nothing provided', () => {
    const result = formatStructuredOutput(undefined, undefined);
    expect(result).toBe('');
  });
});

describe('upsertAutoArtifact', () => {
  beforeEach(() => {
    mockArtifactsFindFirst.mockReset();
    mockArtifactsInsert.mockReset();
    mockArtifactsUpdate.mockReset();
    mockTriggerEvent.mockReset();

    mockArtifactsFindFirst.mockResolvedValue(null);
    mockArtifactsInsert.mockReturnValue({
      values: mock(() => ({
        returning: mock(() => [{ id: 'artifact-1', shareToken: 'generated-share-token' }]),
      })),
    });
  });

  it('creates new artifact when none exists for key', async () => {
    await upsertAutoArtifact({
      workerId: 'worker-1',
      workspaceId: 'ws-1',
      key: 'heartbeat-obj-1',
      type: 'report',
      title: 'Heartbeat: My Mission',
      content: '## Status: ok\nAll good',
      metadata: { autoGenerated: true },
    });

    expect(mockArtifactsInsert).toHaveBeenCalled();
  });

  it('updates existing artifact when key matches', async () => {
    mockArtifactsFindFirst.mockResolvedValue({
      id: 'existing-art',
      shareToken: 'existing-share-token',
    });
    mockArtifactsUpdate.mockReturnValue({
      set: mock(() => ({
        where: mock(() => ({
          returning: mock(() => [{ id: 'existing-art', shareToken: 'existing-share-token' }]),
        })),
      })),
    });

    await upsertAutoArtifact({
      workerId: 'worker-1',
      workspaceId: 'ws-1',
      key: 'heartbeat-obj-1',
      type: 'report',
      title: 'Heartbeat: My Mission',
      content: '## Status: ok\nUpdated',
      metadata: { autoGenerated: true },
    });

    expect(mockArtifactsUpdate).toHaveBeenCalled();
    expect(mockArtifactsInsert).not.toHaveBeenCalled();
  });

  it('skips when workspaceId is missing', async () => {
    await upsertAutoArtifact({
      workerId: 'worker-1',
      workspaceId: '',
      key: 'heartbeat-obj-1',
      type: 'report',
      title: 'Test',
      content: 'Content',
      metadata: {},
    });

    expect(mockArtifactsFindFirst).not.toHaveBeenCalled();
    expect(mockArtifactsInsert).not.toHaveBeenCalled();
  });
});
