import { describe, it, expect, beforeEach, mock } from 'bun:test';

const mockArtifactsFindFirst = mock(() => null as any);
const mockArtifactsInsert = mock(() => ({
  values: mock(() => ({
    returning: mock(() => [{ id: 'artifact-1', shareToken: 'test-share-token' }]),
  })),
}));
const mockArtifactsUpdate = mock(() => ({
  set: mock(() => ({
    where: mock(() => ({
      returning: mock(() => [{ id: 'artifact-1', shareToken: 'existing-share-token' }]),
    })),
  })),
}));
const mockTriggerEvent = mock(() => Promise.resolve());
const mockShouldNotifyOnArtifact = mock(async () => false);
const mockNotifyArtifactReady = mock(async () => {});

mock.module('@buildd/core/db', () => ({
  db: {
    query: {
      artifacts: { findFirst: mockArtifactsFindFirst },
    },
    insert: () => mockArtifactsInsert(),
    update: () => mockArtifactsUpdate(),
  },
}));

mock.module('@/lib/artifact-notify', () => ({
  shouldNotifyOnArtifact: mockShouldNotifyOnArtifact,
  notifyArtifactReady: mockNotifyArtifactReady,
}));

mock.module('drizzle-orm', () => ({
  eq: (field: any, value: any) => ({ field, value, type: 'eq' }),
  and: (...conditions: any[]) => ({ conditions, type: 'and' }),
}));

mock.module('@buildd/core/db/schema', () => ({
  artifacts: 'artifacts',
}));

mock.module('@/lib/pusher', () => ({
  triggerEvent: mockTriggerEvent,
  channels: {
    worker: (id: string) => `worker-${id}`,
    workspace: (id: string) => `workspace-${id}`,
  },
  events: {
    WORKER_PROGRESS: 'worker:progress',
  },
}));

// NOTE: do NOT globally mock 'crypto' here. mock.module is global + persistent
// in bun (not undone by mock.restore), so a partial crypto stub leaks a frozen
// randomBytes / missing createHash into later files (e.g. claude-oauth-login's
// PKCE verifier). generateShareToken is tested against the real crypto below.

import {
  generateShareToken,
  formatStructuredOutput,
  upsertAutoArtifact,
} from './artifact-helpers';

describe('generateShareToken', () => {
  it('returns a string token', () => {
    const token = generateShareToken();
    expect(typeof token).toBe('string');
    expect(token.length).toBeGreaterThan(0);
  });
});

describe('formatStructuredOutput', () => {
  it('formats heartbeat output as markdown', () => {
    const output = {
      status: 'ok',
      summary: 'All systems running normally',
      checksPerformed: ['CI pipeline status', 'Error rate check'],
      actionsPerformed: [],
    };
    const result = formatStructuredOutput(output, 'Task summary here');

    expect(result).toContain('## Status: ok');
    expect(result).toContain('All systems running normally');
    expect(result).toContain('CI pipeline status');
    expect(result).toContain('Error rate check');
  });

  it('formats heartbeat with actions performed', () => {
    const output = {
      status: 'action_taken',
      summary: 'Restarted staging',
      checksPerformed: ['Server health'],
      actionsPerformed: ['Restarted staging server'],
    };
    const result = formatStructuredOutput(output);

    expect(result).toContain('## Status: action_taken');
    expect(result).toContain('Restarted staging server');
  });

  it('renders generic structured output as key-value pairs', () => {
    const output = {
      recommendation: 'Use option B',
      reasoning: 'Better performance',
    };
    const result = formatStructuredOutput(output);

    expect(result).toContain('recommendation');
    expect(result).toContain('Use option B');
  });

  it('uses summary fallback when no structuredOutput', () => {
    const result = formatStructuredOutput(undefined, 'Just a summary');
    expect(result).toBe('Just a summary');
  });

  it('returns empty string when nothing provided', () => {
    const result = formatStructuredOutput(undefined, undefined);
    expect(result).toBe('');
  });
});

describe('upsertAutoArtifact', () => {
  beforeEach(() => {
    mockArtifactsFindFirst.mockReset();
    mockArtifactsInsert.mockReset();
    mockArtifactsUpdate.mockReset();
    mockTriggerEvent.mockReset();
    mockShouldNotifyOnArtifact.mockReset();
    mockNotifyArtifactReady.mockReset();

    mockArtifactsFindFirst.mockResolvedValue(null);
    mockArtifactsInsert.mockReturnValue({
      values: mock(() => ({
        returning: mock(() => [{ id: 'artifact-1', shareToken: 'generated-share-token' }]),
      })),
    });
    mockShouldNotifyOnArtifact.mockResolvedValue(false);
  });

  it('creates new artifact when none exists for key', async () => {
    await upsertAutoArtifact({
      workerId: 'worker-1',
      workspaceId: 'ws-1',
      key: 'heartbeat-obj-1',
      type: 'report',
      title: 'Heartbeat: My Mission',
      content: '## Status: ok\nAll good',
      metadata: { autoGenerated: true },
    });

    expect(mockArtifactsInsert).toHaveBeenCalled();
  });

  it('updates existing artifact when key matches', async () => {
    mockArtifactsFindFirst.mockResolvedValue({
      id: 'existing-art',
      shareToken: 'existing-share-token',
    });
    mockArtifactsUpdate.mockReturnValue({
      set: mock(() => ({
        where: mock(() => ({
          returning: mock(() => [{ id: 'existing-art', shareToken: 'existing-share-token' }]),
        })),
      })),
    });

    await upsertAutoArtifact({
      workerId: 'worker-1',
      workspaceId: 'ws-1',
      key: 'heartbeat-obj-1',
      type: 'report',
      title: 'Heartbeat: My Mission',
      content: '## Status: ok\nUpdated',
      metadata: { autoGenerated: true },
    });

    expect(mockArtifactsUpdate).toHaveBeenCalled();
    expect(mockArtifactsInsert).not.toHaveBeenCalled();
  });

  it('inserts the artifact private with no share token', async () => {
    // The schema's contract: a share token exists only after an explicit Share.
    let capturedValues: any = null;
    mockArtifactsInsert.mockReturnValue({
      values: mock((vals: any) => {
        capturedValues = vals;
        return { returning: mock(() => [{ id: 'artifact-1', ...vals }]) };
      }),
    });

    await upsertAutoArtifact({
      workerId: 'worker-1',
      workspaceId: 'ws-1',
      key: 'mission-obj-1',
      type: 'report',
      title: 'Mission — Latest',
      content: 'Body',
      metadata: { autoGenerated: true },
    });

    expect(capturedValues.shareToken).toBeNull();
    expect(capturedValues.visibility).toBe('private');
  });

  it('never broadcasts a share token over Pusher', async () => {
    mockArtifactsInsert.mockReturnValue({
      values: mock(() => ({
        returning: mock(() => [
          { id: 'artifact-1', title: 'Mission — Latest', shareToken: 'leaked-token', visibility: 'public' },
        ]),
      })),
    });

    await upsertAutoArtifact({
      workerId: 'worker-1',
      workspaceId: 'ws-1',
      key: 'mission-obj-1',
      type: 'report',
      title: 'Mission — Latest',
      content: 'Body',
      metadata: {},
    });

    expect(mockTriggerEvent).toHaveBeenCalledTimes(2);
    for (const call of mockTriggerEvent.mock.calls as any[]) {
      const payload = call[2];
      expect(payload.artifact.shareToken).toBeUndefined();
      expect(JSON.stringify(payload)).not.toContain('leaked-token');
      // The rest of the row still travels.
      expect(payload.artifact.id).toBe('artifact-1');
    }
  });

  it('never broadcasts a share token when updating an existing artifact', async () => {
    mockArtifactsFindFirst.mockResolvedValue({ id: 'existing-art', shareToken: 'existing-share-token' });
    mockArtifactsUpdate.mockReturnValue({
      set: mock(() => ({
        where: mock(() => ({
          returning: mock(() => [{ id: 'existing-art', shareToken: 'existing-share-token' }]),
        })),
      })),
    });

    await upsertAutoArtifact({
      workerId: 'worker-1',
      workspaceId: 'ws-1',
      key: 'mission-obj-1',
      type: 'report',
      title: 'Mission — Latest',
      content: 'Body',
      metadata: {},
    });

    for (const call of mockTriggerEvent.mock.calls as any[]) {
      expect(JSON.stringify(call[2])).not.toContain('existing-share-token');
    }
  });

  it('skips when workspaceId is missing', async () => {
    await upsertAutoArtifact({
      workerId: 'worker-1',
      workspaceId: '',
      key: 'heartbeat-obj-1',
      type: 'report',
      title: 'Test',
      content: 'Content',
      metadata: {},
    });

    expect(mockArtifactsFindFirst).not.toHaveBeenCalled();
    expect(mockArtifactsInsert).not.toHaveBeenCalled();
  });

  it('does not notify when taskId is not provided', async () => {
    await upsertAutoArtifact({
      workerId: 'worker-1',
      workspaceId: 'ws-1',
      key: 'heartbeat-obj-1',
      type: 'report',
      title: 'Test',
      content: 'Content',
      metadata: {},
    });

    expect(mockShouldNotifyOnArtifact).not.toHaveBeenCalled();
    expect(mockNotifyArtifactReady).not.toHaveBeenCalled();
  });

  it('does not notify when shouldNotifyOnArtifact returns false', async () => {
    mockShouldNotifyOnArtifact.mockResolvedValue(false);

    await upsertAutoArtifact({
      workerId: 'worker-1',
      workspaceId: 'ws-1',
      key: 'heartbeat-obj-1',
      type: 'report',
      title: 'Test',
      content: 'Content',
      metadata: {},
      taskId: 'task-1',
    });

    expect(mockShouldNotifyOnArtifact).toHaveBeenCalledWith(
      expect.objectContaining({ id: 'artifact-1' }),
      'task-1'
    );
    expect(mockNotifyArtifactReady).not.toHaveBeenCalled();
  });

  it('sends notification when shouldNotifyOnArtifact returns true', async () => {
    mockShouldNotifyOnArtifact.mockResolvedValue(true);

    await upsertAutoArtifact({
      workerId: 'worker-1',
      workspaceId: 'ws-1',
      key: 'heartbeat-obj-1',
      type: 'report',
      title: 'Test Report',
      content: 'Content',
      metadata: {},
      taskId: 'task-1',
    });

    expect(mockNotifyArtifactReady).toHaveBeenCalledTimes(1);
    const [artifact, taskId, workspaceId] = mockNotifyArtifactReady.mock.calls[0] as any[];
    expect(artifact.id).toBe('artifact-1');
    expect(taskId).toBe('task-1');
    expect(workspaceId).toBe('ws-1');
  });

  it('does not notify on upsert when content and title are unchanged', async () => {
    // First, set up existing artifact
    const existing = {
      id: 'existing-art',
      shareToken: 'existing-share-token',
      content: 'Original content',
      title: 'Original title',
    };
    mockArtifactsFindFirst.mockResolvedValue(existing);
    mockArtifactsUpdate.mockReturnValue({
      set: mock(() => ({
        where: mock(() => ({
          returning: mock(() => [{ id: existing.id, shareToken: existing.shareToken, ...existing }]),
        })),
      })),
    });
    mockShouldNotifyOnArtifact.mockResolvedValue(true);

    // Upsert with the same content and title
    await upsertAutoArtifact({
      workerId: 'worker-1',
      workspaceId: 'ws-1',
      key: 'heartbeat-obj-1',
      type: 'report',
      title: 'Original title',
      content: 'Original content',
      metadata: { autoGenerated: true },
      taskId: 'task-1',
    });

    // Even though shouldNotifyOnArtifact returns true, we should not notify
    // because content and title didn't change
    expect(mockNotifyArtifactReady).not.toHaveBeenCalled();
  });

  it('notifies on upsert when content changed', async () => {
    const existing = {
      id: 'existing-art',
      shareToken: 'existing-share-token',
      content: 'Original content',
      title: 'Original title',
    };
    mockArtifactsFindFirst.mockResolvedValue(existing);
    mockArtifactsUpdate.mockReturnValue({
      set: mock(() => ({
        where: mock(() => ({
          returning: mock(() => [{ id: existing.id, shareToken: existing.shareToken, content: 'New content', title: 'Original title' }]),
        })),
      })),
    });
    mockShouldNotifyOnArtifact.mockResolvedValue(true);

    await upsertAutoArtifact({
      workerId: 'worker-1',
      workspaceId: 'ws-1',
      key: 'heartbeat-obj-1',
      type: 'report',
      title: 'Original title',
      content: 'New content',
      metadata: { autoGenerated: true },
      taskId: 'task-1',
    });

    // Content changed, so should notify
    expect(mockNotifyArtifactReady).toHaveBeenCalledTimes(1);
  });

  it('notifies on upsert when title changed', async () => {
    const existing = {
      id: 'existing-art',
      shareToken: 'existing-share-token',
      content: 'Original content',
      title: 'Original title',
    };
    mockArtifactsFindFirst.mockResolvedValue(existing);
    mockArtifactsUpdate.mockReturnValue({
      set: mock(() => ({
        where: mock(() => ({
          returning: mock(() => [{ id: existing.id, shareToken: existing.shareToken, content: 'Original content', title: 'New title' }]),
        })),
      })),
    });
    mockShouldNotifyOnArtifact.mockResolvedValue(true);

    await upsertAutoArtifact({
      workerId: 'worker-1',
      workspaceId: 'ws-1',
      key: 'heartbeat-obj-1',
      type: 'report',
      title: 'New title',
      content: 'Original content',
      metadata: { autoGenerated: true },
      taskId: 'task-1',
    });

    // Title changed, so should notify
    expect(mockNotifyArtifactReady).toHaveBeenCalledTimes(1);
  });
});
