/**
 * Artifact prominence — which artifacts a human is meant to REVIEW.
 *
 * Agents emit two very different kinds of row into the same `artifacts` table:
 * documents written to be read (a report, an analysis, a recommendation), and
 * the exhaust of doing the work (screenshots, diffs, uploaded files, machine
 * markers). The table has no review/deliverable/prominence column, so the
 * distinction has to be derived — and it must be derived in ONE place, or the
 * page, the API and the MCP tool surface each invent their own rule. This
 * module is that place.
 *
 * The rule, in order:
 *
 *  1. `visibility === 'public'` → review. Public is only ever set by an
 *     explicit Share action, which also mints a bearer token. That is an
 *     unambiguous human decision to publish, whatever the type.
 *
 *  2. Type partition. `type` is the one signal every writer must supply and
 *     validate against the shared vocabulary, so it carries the most intent:
 *      - REVIEW types are prose written for a reader. Admitted on type alone —
 *        requiring a key as well would hide the common `create_artifact({type:
 *        'report'})` call, which is the single most deliberate thing an agent
 *        does here.
 *      - BYPRODUCT types are captures, evidence and machine markers. Excluded
 *        even when keyed or container-scoped: a key on a capture makes it
 *        addressable (upsertable via the unique `(workspaceId, key)` index),
 *        not review-worthy. The CI conformance marker is a keyed, workspace-
 *        level `data` row rewritten by a machine credential on every run.
 *      - WORKING types are review-shaped prose that the loop itself emits for
 *        every worker (`impl_plan`). Admitted only with a deliberate `key` or
 *        an owning mission/initiative — i.e. someone named it or filed it
 *        against a container on purpose.
 *
 *  3. Unknown types (the column is free text) are treated like WORKING: they
 *     need a key or a container. Fail quiet rather than flooding the view.
 *
 * One exception sits between 1 and 2: a visual-audit screenshot
 * (`isAuditScreenshot`) is review evidence, not a byproduct
 * (docs/design/visual-qa-auditor.md, "Where the screenshots show"). It is
 * marked by a qa-area storage key (`buildAuditScreenshotKey`) or by a
 * `metadata.qa` object — the key because PATCH can rewrite metadata but never
 * the key, the metadata because that is what the auditor writes. Either
 * marker also makes the share route refuse to publish it.
 *
 * Deliberately NOT used as signals:
 *  - `metadata.autoGenerated`. The auto mission rollup is machine-written but
 *    is exactly the digest a human reviews, and the unique key index caps it at
 *    one row per mission, so it adds no volume.
 *  - `content` length / presence. An artifact can legitimately carry its body
 *    in R2 (`storageKey`) with a NULL `content`.
 */
import { ArtifactType, type ArtifactTypeValue } from '@buildd/shared';
import { isAuditStorageKey } from './storage-keys';

/** Prose written to be read. Prominent on type alone. */
export const REVIEW_ARTIFACT_TYPES = [
  ArtifactType.REPORT,
  ArtifactType.ANALYSIS,
  ArtifactType.RECOMMENDATION,
  ArtifactType.WALKTHROUGH,
  ArtifactType.SUMMARY,
  ArtifactType.CONTENT,
  ArtifactType.EMAIL_DRAFT,
  ArtifactType.SOCIAL_POST,
  ArtifactType.ALERT,
] as const satisfies readonly ArtifactTypeValue[];

/**
 * Review-shaped, but emitted by the loop for essentially every worker — needs
 * a second signal (key or container) before it counts as a deliverable.
 */
export const WORKING_ARTIFACT_TYPES = [
  ArtifactType.IMPL_PLAN,
] as const satisfies readonly ArtifactTypeValue[];

/** Captures, evidence and machine markers. Never prominent on their own. */
export const BYPRODUCT_ARTIFACT_TYPES = [
  ArtifactType.SCREENSHOT,
  ArtifactType.RECORDING,
  ArtifactType.DIFF,
  ArtifactType.FILE,
  ArtifactType.DATA,
  ArtifactType.LINK,
  ArtifactType.CALENDAR_EVENT,
] as const satisfies readonly ArtifactTypeValue[];

const REVIEW_SET: ReadonlySet<string> = new Set(REVIEW_ARTIFACT_TYPES);
const BYPRODUCT_SET: ReadonlySet<string> = new Set(BYPRODUCT_ARTIFACT_TYPES);

/**
 * The subset of an artifact row the predicate reads. Kept structural so the
 * server component, the client list and any API caller can all pass what they
 * already have without a conversion step.
 */
export interface ArtifactProminenceInput {
  type: string;
  key?: string | null;
  missionId?: string | null;
  initiativeId?: string | null;
  visibility?: 'private' | 'public' | null;
  storageKey?: string | null;
  /** Read only for `metadata.qa` (`isAuditScreenshot`) — see the module doc. */
  metadata?: Record<string, unknown> | null;
}

/**
 * A screenshot captured by the visual auditor: a qa-area storage key, or a
 * `metadata.qa` object. Only the marker's presence is read here; the fields
 * are parsed (defensively) by `mission-visual-review`.
 */
export function isAuditScreenshot(
  artifact: Pick<ArtifactProminenceInput, 'type' | 'storageKey' | 'metadata'>,
): boolean {
  if (artifact.type !== ArtifactType.SCREENSHOT) return false;
  if (isAuditStorageKey(artifact.storageKey)) return true;
  const qa = artifact.metadata?.qa;
  return typeof qa === 'object' && qa !== null && !Array.isArray(qa);
}

/** True when the artifact was deliberately produced for a human to review. */
export function isReviewArtifact(artifact: ArtifactProminenceInput): boolean {
  if (artifact.visibility === 'public') return true;
  if (isAuditScreenshot(artifact)) return true;
  if (BYPRODUCT_SET.has(artifact.type)) return false;
  if (REVIEW_SET.has(artifact.type)) return true;
  return Boolean(artifact.key) || Boolean(artifact.missionId) || Boolean(artifact.initiativeId);
}

/** Split a list into review-worthy and incidental, preserving order in each. */
export function partitionByReview<T extends ArtifactProminenceInput>(
  list: readonly T[],
): { review: T[]; incidental: T[] } {
  const review: T[] = [];
  const incidental: T[] = [];
  for (const item of list) {
    (isReviewArtifact(item) ? review : incidental).push(item);
  }
  return { review, incidental };
}
