/**
 * PR activity comment — the "buildd is on it" surface.
 *
 * One sticky comment per pull request, edited in place, so a human watching the
 * PR can see that an agent picked the work up without opening the dashboard:
 * reviewer dispatched, CI failure being fixed, review feedback being applied,
 * escalation to a human.
 *
 * The comment carries its own history in a hidden state block
 * (`<!-- buildd-activity-state:{...} -->`), so appending an entry needs no
 * schema column — we read the existing comment, append, and PATCH it back.
 *
 * Every function here is best-effort: a GitHub failure logs and returns
 * `{ action: 'failed' }`. Posting a status comment must never break the
 * lifecycle step that triggered it.
 */

export const ACTIVITY_COMMENT_MARKER = '<!-- buildd-activity -->';

/**
 * Animated spinner shown in the header while buildd is mid-flight.
 *
 * GitHub routes comment images through its camo proxy, which passes animated
 * GIFs through untouched — animated SVG and CSS do not survive comment
 * sanitization, so a GIF is the only thing that actually moves. The asset is
 * generated by `scripts/generate-pr-spinner-gif.ts`.
 *
 * camo fetches the image server-side, so the origin must be publicly
 * reachable: a localhost dev URL would render as a broken image on GitHub.
 * Anything that isn't a public https origin falls back to production.
 */
function assetOrigin(): string {
  const configured = process.env.NEXT_PUBLIC_APP_URL;
  const usable =
    configured?.startsWith('https://') &&
    !configured.includes('localhost') &&
    !configured.includes('127.0.0.1');
  return usable ? configured!.replace(/\/$/, '') : 'https://buildd.dev';
}

export const SPINNER_PATH = '/github/pr-working.gif';
const STATE_PREFIX = '<!-- buildd-activity-state:';
const STATE_SUFFIX = ' -->';

/** Entries older than this fall off the log so the comment stays readable. */
export const MAX_ACTIVITY_ENTRIES = 12;

export type PrActivityKind =
  | 'reviewing'
  | 'review_approved'
  | 'review_approved_awaiting_human'
  | 'review_changes_requested'
  | 'review_escalated'
  | 'human_review_required'
  | 'ci_fixing'
  | 'ci_exhausted'
  | 'changes_pushed';

export interface PrActivityEntry {
  kind: PrActivityKind;
  /** One-line qualifier rendered after the headline (e.g. "attempt 2 of 3"). */
  detail?: string | null;
  /** Link rendered alongside the entry (CI run, commit, task). */
  url?: string | null;
  /** ISO timestamp. Defaults to now. */
  at?: string;
}

interface Presentation {
  icon: string;
  /**
   * True while buildd still has work in hand for this PR. Drives the animated
   * header spinner, so movement always means "an agent is on it right now" —
   * a terminal state must never keep spinning.
   */
  working: boolean;
  /** Short label used in both the headline and the log line. */
  label: string;
  /** Sentence under the headline explaining what buildd is doing right now. */
  status: string;
}

const PRESENTATION: Record<PrActivityKind, Presentation> = {
  reviewing: {
    icon: '🔍',
    working: true,
    label: 'Reviewing changes',
    status: 'A buildd reviewer agent is going through this PR now.',
  },
  review_approved: {
    icon: '✅',
    working: true,
    label: 'Review passed',
    status: 'The reviewer approved these changes — merging once checks are green.',
  },
  review_approved_awaiting_human: {
    icon: '✅',
    working: false,
    label: 'Review passed — awaiting human merge',
    status: 'The reviewer approved these changes. Merge policy leaves the merge to a human.',
  },
  review_changes_requested: {
    icon: '🔁',
    working: true,
    label: 'Applying review feedback',
    status: 'The reviewer requested changes — buildd is pushing fixes to this branch.',
  },
  review_escalated: {
    icon: '🚨',
    working: false,
    label: 'Escalated to a human',
    status: 'The reviewer stopped and handed this PR to a human.',
  },
  human_review_required: {
    icon: '👀',
    working: false,
    label: 'Human review required',
    status: 'Merge policy requires a human to review this PR — buildd will not merge it.',
  },
  ci_fixing: {
    icon: '🔧',
    working: true,
    label: 'CI failed — fixing',
    status: 'buildd picked up the CI failure and is working on a fix on this branch.',
  },
  ci_exhausted: {
    icon: '🚨',
    working: false,
    label: 'CI still failing — needs a human',
    status: 'buildd used up its CI retries and stopped. This PR needs a human.',
  },
  changes_pushed: {
    icon: '⬆️',
    working: true,
    label: 'Fixes pushed',
    status: 'buildd pushed new commits to this branch — waiting on checks.',
  },
};

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

/** Deterministic UTC stamp — no locale dependence, stable across environments. */
function formatUtc(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return 'unknown time';
  const month = MONTHS[d.getUTCMonth()];
  const day = d.getUTCDate();
  const hh = String(d.getUTCHours()).padStart(2, '0');
  const mm = String(d.getUTCMinutes()).padStart(2, '0');
  return `${month} ${day}, ${hh}:${mm} UTC`;
}

function normalize(entry: PrActivityEntry): Required<Pick<PrActivityEntry, 'kind' | 'at'>> & PrActivityEntry {
  return {
    kind: entry.kind,
    detail: entry.detail ?? null,
    url: entry.url ?? null,
    at: entry.at ?? new Date().toISOString(),
  };
}

/** Render the full comment body (marker, headline, activity log, state block). */
export function renderPrActivityComment(entries: PrActivityEntry[]): string {
  const kept = entries.slice(-MAX_ACTIVITY_ENTRIES).map(normalize);
  const latest = kept[kept.length - 1];
  const head = latest ? PRESENTATION[latest.kind] : null;

  const lines = kept.map((entry) => {
    const p = PRESENTATION[entry.kind];
    const detail = entry.detail ? ` — ${entry.detail}` : '';
    const link = entry.url ? ` ([details](${entry.url}))` : '';
    return `- ${p.icon} \`${formatUtc(entry.at)}\` **${p.label}**${detail}${link}`;
  });

  // The spinner is the whole point of the header: it moves while buildd is
  // mid-flight, and is replaced by a static icon the moment it isn't.
  const marker = head?.working
    ? `<img src="${assetOrigin()}${SPINNER_PATH}" width="14" height="14" alt="working" align="top" />`
    : (head?.icon ?? '');
  const since = latest ? ` <sub>· since ${formatUtc(latest.at)}</sub>` : '';

  return [
    ACTIVITY_COMMENT_MARKER,
    '### 🤖 buildd',
    '',
    head ? `${marker} **${head.label}** — ${head.status}${since}` : '_No activity yet._',
    '',
    '<details open><summary>Activity</summary>',
    '',
    ...lines,
    '',
    '</details>',
    '',
    '<sub>Posted by [buildd](https://buildd.dev) and edited in place as work progresses.</sub>',
    `${STATE_PREFIX}${JSON.stringify({ v: 1, entries: kept })}${STATE_SUFFIX}`,
  ].join('\n');
}

/** Recover the entry list from an existing comment body. Corrupt state → `[]`. */
export function parsePrActivityState(body: string): PrActivityEntry[] {
  const start = body.indexOf(STATE_PREFIX);
  if (start === -1) return [];
  const from = start + STATE_PREFIX.length;
  const end = body.indexOf(STATE_SUFFIX, from);
  if (end === -1) return [];
  try {
    const parsed = JSON.parse(body.slice(from, end)) as { entries?: unknown };
    if (!Array.isArray(parsed.entries)) return [];
    return parsed.entries.filter(
      (e): e is PrActivityEntry =>
        !!e && typeof e === 'object' && typeof (e as PrActivityEntry).kind === 'string' &&
        (e as PrActivityEntry).kind in PRESENTATION,
    );
  } catch {
    return [];
  }
}

export type AppendResult =
  | { action: 'created' | 'updated' | 'unchanged'; commentId: number }
  | { action: 'failed' };

async function getGithubApi() {
  const { githubApi } = await import('@/lib/github');
  return githubApi;
}

/** Locate the sticky comment. Scans up to 3 pages — ours is posted early. */
async function findActivityComment(
  githubApi: (installationId: number, path: string, options?: RequestInit) => Promise<unknown>,
  installationId: number,
  repoFullName: string,
  prNumber: number,
): Promise<{ id: number; body: string } | null> {
  const perPage = 100;
  for (let page = 1; page <= 3; page++) {
    const raw = (await githubApi(
      installationId,
      `/repos/${repoFullName}/issues/${prNumber}/comments?per_page=${perPage}&page=${page}`,
    )) as Array<{ id: number; body?: string | null }> | null;
    if (!Array.isArray(raw) || raw.length === 0) return null;
    const hit = raw.find((c) => typeof c.body === 'string' && c.body.includes(ACTIVITY_COMMENT_MARKER));
    if (hit) return { id: hit.id, body: hit.body as string };
    if (raw.length < perPage) return null;
  }
  return null;
}

/**
 * Append one entry to the PR's sticky buildd comment, creating it if absent.
 *
 * A repeat of the newest entry (same kind + detail) is dropped rather than
 * appended, so a webhook redelivery doesn't stack identical lines.
 *
 * `onlyIfPresent` skips creating a new comment — used for follow-up signals
 * (a push to the branch) that are only interesting once buildd has already
 * announced it is working the PR.
 */
export async function appendPrActivity(params: {
  installationId: number;
  repoFullName: string;
  prNumber: number;
  entry: PrActivityEntry;
  onlyIfPresent?: boolean;
}): Promise<AppendResult> {
  const { installationId, repoFullName, prNumber, entry, onlyIfPresent } = params;
  try {
    const githubApi = await getGithubApi();
    const existing = await findActivityComment(githubApi, installationId, repoFullName, prNumber);
    const next = normalize(entry);

    if (existing) {
      const entries = parsePrActivityState(existing.body);
      const last = entries[entries.length - 1];
      if (last && last.kind === next.kind && (last.detail ?? null) === (next.detail ?? null)) {
        return { action: 'unchanged', commentId: existing.id };
      }
      await githubApi(installationId, `/repos/${repoFullName}/issues/comments/${existing.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ body: renderPrActivityComment([...entries, next]) }),
      });
      return { action: 'updated', commentId: existing.id };
    }

    if (onlyIfPresent) {
      return { action: 'unchanged', commentId: 0 };
    }

    const created = (await githubApi(installationId, `/repos/${repoFullName}/issues/${prNumber}/comments`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ body: renderPrActivityComment([next]) }),
    })) as { id?: number } | null;
    return { action: 'created', commentId: created?.id ?? 0 };
  } catch (error) {
    console.warn(
      `[pr-activity] Could not post ${entry.kind} activity on ${repoFullName}#${prNumber}:`,
      error instanceof Error ? error.message : error,
    );
    return { action: 'failed' };
  }
}
