/**
 * PR activity comment — the "buildd is on it" surface.
 *
 * One sticky comment per pull request, edited in place, so a human watching the
 * PR can see that an agent picked the work up without opening the dashboard:
 * reviewer dispatched, CI failure being fixed, review feedback being applied,
 * escalation to a human.
 *
 * The comment carries its own history in a hidden state block
 * (`<!-- buildd-activity-state:{...} -->`), so appending an entry needs no
 * schema column — we read the existing comment, append, and PATCH it back.
 *
 * Every function here is best-effort: a GitHub failure logs and returns
 * `{ action: 'failed' }`. Posting a status comment must never break the
 * lifecycle step that triggered it.
 *
 * Copy rules (status words, length limits, glyph set) live next to this file in
 * `pr-activity-comment.STYLE.md`. Read it before adding a kind or a label.
 */

import { DEFAULT_TIMEZONE, formatStamp } from '@buildd/core/timezone';

export const ACTIVITY_COMMENT_MARKER = '<!-- buildd-activity -->';

/**
 * Animated spinner shown in the header while buildd is mid-flight.
 *
 * GitHub routes comment images through its camo proxy, which passes animated
 * GIFs through untouched — animated SVG and CSS do not survive comment
 * sanitization, so a GIF is the only thing that actually moves. The asset is
 * generated by `scripts/generate-pr-spinner-gif.ts`.
 *
 * camo fetches the image server-side, so the origin must be publicly
 * reachable: a localhost dev URL would render as a broken image on GitHub.
 * Anything that isn't a public https origin falls back to production.
 */
function assetOrigin(): string {
  const configured = process.env.NEXT_PUBLIC_APP_URL;
  const usable =
    configured?.startsWith('https://') &&
    !configured.includes('localhost') &&
    !configured.includes('127.0.0.1');
  return usable ? configured!.replace(/\/$/, '') : 'https://buildd.dev';
}

export const SPINNER_PATH = '/github/pr-working.gif';
const STATE_PREFIX = '<!-- buildd-activity-state:';
const STATE_SUFFIX = ' -->';

/** Entries older than this fall off the log so the comment stays readable. */
export const MAX_ACTIVITY_ENTRIES = 12;

/** A row's inline qualifier is cut here; anything longer belongs in `note`. */
export const MAX_DETAIL_CHARS = 60;

/** A collapsed note is cut here — the task or review holds the full text. */
export const MAX_NOTE_CHARS = 1200;

export type PrActivityKind =
  | 'reviewing'
  | 'review_approved'
  | 'review_approved_awaiting_human'
  | 'review_changes_requested'
  | 'review_escalated'
  | 'review_failed'
  | 'lede_corrected'
  | 'human_review_required'
  | 'ci_fixing'
  | 'ci_exhausted'
  | 'fix_started'
  | 'changes_pushed'
  | 'review_superseded_by_merge'
  | 'human_applied_recommendation'
  | 'human_override_merge'
  | 'merged'
  | 'closed_unmerged';

export interface PrActivityEntry {
  kind: PrActivityKind;
  /**
   * Short inline qualifier, a few words ("schema drift · diagnose only").
   * Anything over `MAX_DETAIL_CHARS` is collapsed like a `note` instead of
   * pasted into the row.
   */
  detail?: string | null;
  /**
   * Long text (reviewer feedback, an escalation reason, the original lede).
   * Never inline: always rendered collapsed under its row.
   */
  note?: string | null;
  /** Fix iteration this entry is about — "fix 1 of 3". */
  iteration?: number | null;
  maxIterations?: number | null;
  /** Short commit sha, for `changes_pushed`. */
  sha?: string | null;
  /** The buildd task doing the work — the link a reader follows from a queued fix. */
  taskUrl?: string | null;
  /** Any other link (CI run, commit). */
  url?: string | null;
  /** ISO timestamp. Defaults to now. */
  at?: string;
}

type NormalizedEntry = PrActivityEntry & { at: string };

/**
 * Glyphs. The copy style guide (`pr-activity-comment.STYLE.md`) is the
 * contract; this is its implementation. A glyph appears only when it carries a
 * meaning the words don't — most rows have none.
 */
export const GLYPH = {
  /** Nothing is running: queued, or waiting on checks/another party. */
  waiting: '○',
  /** An outcome that went well: approved, merged. */
  done: '✓',
  /** A human has to act. */
  human: '⚑',
  /** Ended without landing. */
  ended: '✕',
} as const;

type Tone = 'working' | keyof typeof GLYPH | 'plain';

interface Rendered {
  /** `working` shows the animated spinner in the header; rows never animate. */
  tone: Tone;
  /** Timeline row text, and the header headline when this entry is current. */
  label: string;
  /** Shorter header wording, when the row label carries history the header doesn't need. */
  headline?: string;
  /** Header-only tail, e.g. "waiting for a worker". Omitted from the row. */
  status?: string;
  /** Summary text on the collapsed note. */
  noteLabel?: string;
  /** Label for `url`. */
  urlLabel?: string;
  /** Not a state change — never becomes the header on its own. */
  aside?: boolean;
}

/** Running facts the timeline has established by the time it reaches an entry. */
interface Story {
  /** The newest fix iteration seen so far. */
  fix: { iteration: number | null; maxIterations: number | null } | null;
}

function fixText(e: { iteration?: number | null; maxIterations?: number | null } | null | undefined): string {
  if (!e || e.iteration == null) return 'fix';
  return e.maxIterations != null ? `fix ${e.iteration} of ${e.maxIterations}` : `fix ${e.iteration}`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function hasIteration(e: PrActivityEntry): boolean {
  return e.iteration != null;
}

/**
 * The status vocabulary. Every label here is listed in the style guide — add
 * one there first.
 */
function present(e: NormalizedEntry, story: Story): Rendered {
  switch (e.kind) {
    case 'reviewing':
      return story.fix
        ? { tone: 'working', label: story.fix.iteration != null ? `Re-reviewing · after ${fixText(story.fix)}` : 'Re-reviewing' }
        : { tone: 'working', label: 'Reviewing' };
    case 'review_changes_requested':
      return {
        tone: 'waiting',
        label: `Changes requested · ${fixText(e)} queued`,
        headline: `${capitalize(fixText(e))} queued`,
        status: 'waiting for a worker',
        noteLabel: 'Reviewer feedback',
      };
    case 'ci_fixing':
      return {
        tone: 'waiting',
        label: `CI failed · ${fixText(e)} queued`,
        headline: `CI ${fixText(e)} queued`,
        status: 'waiting for a worker',
        noteLabel: 'Details',
        urlLabel: 'CI run',
      };
    case 'human_applied_recommendation':
      return {
        tone: 'waiting',
        label: 'Recommendation applied · fix queued',
        status: 'waiting for a worker',
      };
    case 'fix_started':
      // Only ever written once a worker has CLAIMED the fix task. This is the
      // one state allowed to say buildd is changing the branch.
      return { tone: 'working', label: `Fixing · ${fixText(hasIteration(e) ? e : story.fix)}` };
    case 'changes_pushed': {
      const sha = e.sha ? `\`${e.sha}\`` : null;
      return {
        tone: 'waiting',
        label: sha ? `Pushed ${sha}` : 'Pushed',
        status: 'waiting on checks',
        urlLabel: 'commit',
      };
    }
    case 'review_approved':
      return { tone: 'done', label: 'Approved', status: 'merging once checks pass', noteLabel: 'Summary' };
    case 'review_approved_awaiting_human':
      return { tone: 'done', label: 'Approved · ready to merge', status: 'merge policy leaves this to a human', noteLabel: 'Summary' };
    case 'review_escalated':
      return { tone: 'human', label: 'Escalated · needs a human', noteLabel: 'Reason' };
    case 'review_failed':
      return {
        tone: 'human',
        label: 'Review didn’t finish · needs a human',
        status: 'no verdict came back; nothing blocks merging, but nobody reviewed it',
      };
    case 'human_review_required':
      return { tone: 'human', label: 'Human review required', status: 'merge policy', noteLabel: 'Reason' };
    case 'ci_exhausted':
      return { tone: 'human', label: 'CI still failing · needs a human', noteLabel: 'Details', urlLabel: 'CI run' };
    case 'lede_corrected':
      return { tone: 'plain', label: 'Opening line corrected', noteLabel: 'Original', aside: true };
    case 'review_superseded_by_merge':
      return { tone: 'done', label: 'Merged by a human · review cancelled' };
    case 'human_override_merge':
      return { tone: 'done', label: 'Merged · escalation overridden', noteLabel: 'Reason' };
    case 'merged':
      return { tone: 'done', label: 'Merged' };
    case 'closed_unmerged':
      return { tone: 'ended', label: 'Closed without merging' };
  }
}

function advance(story: Story, e: PrActivityEntry): Story {
  if (e.kind === 'review_changes_requested' || e.kind === 'ci_fixing' || e.kind === 'fix_started' || e.kind === 'human_applied_recommendation') {
    return {
      fix: hasIteration(e)
        ? { iteration: e.iteration ?? null, maxIterations: e.maxIterations ?? null }
        : story.fix ?? { iteration: null, maxIterations: null },
    };
  }
  return story;
}

function normalize(entry: PrActivityEntry): NormalizedEntry {
  const out: NormalizedEntry = { kind: entry.kind, at: entry.at ?? new Date().toISOString() };
  // Only set what is present, so the state block stays small and old entries
  // (which carry just kind/detail/url/at) round-trip unchanged.
  if (entry.detail != null) out.detail = entry.detail;
  if (entry.note != null && entry.note.trim()) out.note = clip(entry.note.trim(), MAX_NOTE_CHARS);
  if (entry.iteration != null) out.iteration = entry.iteration;
  if (entry.maxIterations != null) out.maxIterations = entry.maxIterations;
  if (entry.sha != null) out.sha = entry.sha;
  if (entry.taskUrl != null) out.taskUrl = entry.taskUrl;
  if (entry.url != null) out.url = entry.url;
  // Legacy callers put everything in `detail`. Treat anything long as a note.
  if (out.detail && out.detail.length > MAX_DETAIL_CHARS) {
    out.note = out.note ? `${out.detail}\n\n${out.note}` : clip(out.detail, MAX_NOTE_CHARS);
    delete out.detail;
  }
  return out;
}

function clip(s: string, max: number): string {
  return s.length <= max ? s : `${s.slice(0, max - 1).trimEnd()}…`;
}

/** `0m`, `+9m`, `+1h 4m`, `+2d 3h` — elapsed since the first entry. Never goes stale. */
export function formatOffset(fromIso: string, toIso: string): string {
  const ms = new Date(toIso).getTime() - new Date(fromIso).getTime();
  if (!Number.isFinite(ms) || ms < 60_000) return '0m';
  const mins = Math.floor(ms / 60_000);
  if (mins < 60) return `+${mins}m`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return mins % 60 ? `+${hours}h ${mins % 60}m` : `+${hours}h`;
  const days = Math.floor(hours / 24);
  return hours % 24 ? `+${days}d ${hours % 24}h` : `+${days}d`;
}

/**
 * Keep user text inside its `<details>`: a stray tag would close the
 * disclosure early and spill the rest of the comment into it.
 */
function escapeNote(s: string): string {
  return s.replace(/<(\/?)(details|summary)/gi, '&lt;$1$2');
}

function links(e: NormalizedEntry, p: Rendered, seenTasks: Set<string>): string {
  const parts: string[] = [];
  // The same fix task threads through queued → fixing; link it once.
  if (e.taskUrl && !seenTasks.has(e.taskUrl)) {
    seenTasks.add(e.taskUrl);
    parts.push(`[task](${e.taskUrl})`);
  }
  if (e.url) parts.push(`[${p.urlLabel ?? 'details'}](${e.url})`);
  return parts.length ? ` · ${parts.join(' · ')}` : '';
}

function rowGlyph(tone: Tone): string {
  // Rows only mark outcomes. "Waiting" and "working" are header states; on a
  // history row they'd just be decoration.
  return tone === 'done' || tone === 'human' || tone === 'ended' ? `${GLYPH[tone]} ` : '';
}

/**
 * Render the full comment body (marker, status line, timeline, state block).
 *
 * `timezone` is applied at render time and never stored in the state block, so
 * changing a team's zone re-stamps the comment on the next update.
 */
export function renderPrActivityComment(
  entries: PrActivityEntry[],
  timezone: string = DEFAULT_TIMEZONE,
): string {
  const kept = entries.slice(-MAX_ACTIVITY_ENTRIES).map(normalize);
  if (kept.length === 0) {
    return [ACTIVITY_COMMENT_MARKER, '**buildd** · no activity yet', stateBlock(kept)].join('\n');
  }

  const start = kept[0].at;
  let story: Story = { fix: null };
  const rows: string[] = [];
  const seenTasks = new Set<string>();
  let head: { entry: NormalizedEntry; p: Rendered } | null = null;

  for (const e of kept) {
    story = advance(story, e);
    const p = present(e, story);
    if (!p.aside || !head) head = { entry: e, p };

    const detail = e.detail ? ` · ${e.detail}` : '';
    rows.push(`- \`${formatOffset(start, e.at)}\` ${rowGlyph(p.tone)}${p.label}${detail}${links(e, p, seenTasks)}`);
    if (e.note) {
      const body = escapeNote(e.note).split('\n').map((l) => (l ? `  ${l}` : '')).join('\n');
      rows.push(`  <details><summary>${p.noteLabel ?? 'Details'}</summary>`, '', body, '', '  </details>');
    }
  }

  const { entry: current, p: currentP } = head!;
  // Movement means "a worker is on this right now" — never a queued fix.
  const marker = currentP.tone === 'working'
    ? `<img src="${assetOrigin()}${SPINNER_PATH}" width="12" height="12" alt="working" align="absmiddle" />`
    : currentP.tone === 'plain' ? '' : GLYPH[currentP.tone];
  const status = currentP.status ? ` · ${currentP.status}` : '';
  const headLink = current.taskUrl ? ` · [task](${current.taskUrl})` : '';

  return [
    ACTIVITY_COMMENT_MARKER,
    `**buildd** · ${marker ? `${marker} ` : ''}**${currentP.headline ?? currentP.label}**${status}${headLink}`,
    '',
    ...rows,
    '',
    `<sub>Started ${formatStamp(start, timezone)} · edited in place by [buildd](https://buildd.dev)</sub>`,
    stateBlock(kept),
  ].join('\n');
}

function stateBlock(kept: NormalizedEntry[]): string {
  // `>` is escaped so a note containing `-->` can't end the HTML comment early.
  const json = JSON.stringify({ v: 1, entries: kept }).replace(/>/g, '\\u003e');
  return `${STATE_PREFIX}${json}${STATE_SUFFIX}`;
}

const KNOWN_KINDS: ReadonlySet<string> = new Set<PrActivityKind>([
  'reviewing', 'review_approved', 'review_approved_awaiting_human', 'review_changes_requested',
  'review_escalated', 'review_failed', 'lede_corrected', 'human_review_required', 'ci_fixing',
  'ci_exhausted', 'fix_started', 'changes_pushed', 'review_superseded_by_merge',
  'human_applied_recommendation', 'human_override_merge', 'merged', 'closed_unmerged',
]);

/** A webhook redelivery of the newest entry — same kind and the same facts. */
function sameEntry(a: PrActivityEntry, b: PrActivityEntry): boolean {
  return (
    a.kind === b.kind &&
    (a.detail ?? null) === (b.detail ?? null) &&
    (a.iteration ?? null) === (b.iteration ?? null) &&
    (a.sha ?? null) === (b.sha ?? null)
  );
}

/** Dashboard link for a task, for `taskUrl`. */
export function taskActivityUrl(taskId: string): string {
  return `${assetOrigin()}/app/tasks/${taskId}`;
}

/** Recover the entry list from an existing comment body. Corrupt state → `[]`. */
export function parsePrActivityState(body: string): PrActivityEntry[] {
  const start = body.indexOf(STATE_PREFIX);
  if (start === -1) return [];
  const from = start + STATE_PREFIX.length;
  const end = body.indexOf(STATE_SUFFIX, from);
  if (end === -1) return [];
  try {
    const parsed = JSON.parse(body.slice(from, end)) as { entries?: unknown };
    if (!Array.isArray(parsed.entries)) return [];
    return parsed.entries.filter(
      (e): e is PrActivityEntry =>
        !!e && typeof e === 'object' && typeof (e as PrActivityEntry).kind === 'string' &&
        KNOWN_KINDS.has((e as PrActivityEntry).kind),
    );
  } catch {
    return [];
  }
}

export type AppendResult =
  | { action: 'created' | 'updated' | 'unchanged'; commentId: number }
  | { action: 'failed' };

async function getGithubApi() {
  const { githubApi } = await import('@/lib/github');
  return githubApi;
}

/**
 * The zone to stamp this comment in: the owning team's, or UTC.
 *
 * Resolved lazily and defensively — the comment is a best-effort surface, so a
 * missing workspace or an unreachable DB must degrade to UTC rather than skip
 * the update.
 */
async function resolveCommentTimezone(workspaceId?: string | null): Promise<string> {
  if (!workspaceId) return DEFAULT_TIMEZONE;
  try {
    const { getWorkspaceTimezone } = await import('@/lib/team-timezone');
    return await getWorkspaceTimezone(workspaceId);
  } catch {
    return DEFAULT_TIMEZONE;
  }
}

/** Locate the sticky comment. Scans up to 3 pages — ours is posted early. */
async function findActivityComment(
  githubApi: (installationId: number, path: string, options?: RequestInit) => Promise<unknown>,
  installationId: number,
  repoFullName: string,
  prNumber: number,
): Promise<{ id: number; body: string } | null> {
  const perPage = 100;
  for (let page = 1; page <= 3; page++) {
    const raw = (await githubApi(
      installationId,
      `/repos/${repoFullName}/issues/${prNumber}/comments?per_page=${perPage}&page=${page}`,
    )) as Array<{ id: number; body?: string | null }> | null;
    if (!Array.isArray(raw) || raw.length === 0) return null;
    const hit = raw.find((c) => typeof c.body === 'string' && c.body.includes(ACTIVITY_COMMENT_MARKER));
    if (hit) return { id: hit.id, body: hit.body as string };
    if (raw.length < perPage) return null;
  }
  return null;
}

/**
 * Append one entry to the PR's sticky buildd comment, creating it if absent.
 *
 * A repeat of the newest entry (same kind + detail) is dropped rather than
 * appended, so a webhook redelivery doesn't stack identical lines.
 *
 * `onlyIfPresent` skips creating a new comment — used for follow-up signals
 * (a push to the branch) that are only interesting once buildd has already
 * announced it is working the PR.
 *
 * `workspaceId` selects the wall clock: timestamps render in the owning team's
 * timezone. Omit it and the comment stamps in UTC.
 */
export async function appendPrActivity(params: {
  installationId: number;
  repoFullName: string;
  prNumber: number;
  entry: PrActivityEntry;
  onlyIfPresent?: boolean;
  workspaceId?: string | null;
}): Promise<AppendResult> {
  const { installationId, repoFullName, prNumber, entry, onlyIfPresent, workspaceId } = params;
  try {
    const githubApi = await getGithubApi();
    const timezone = await resolveCommentTimezone(workspaceId);
    const existing = await findActivityComment(githubApi, installationId, repoFullName, prNumber);
    const next = normalize(entry);

    if (existing) {
      const entries = parsePrActivityState(existing.body);
      const last = entries[entries.length - 1];
      if (last && sameEntry(normalize(last), next)) {
        return { action: 'unchanged', commentId: existing.id };
      }
      await githubApi(installationId, `/repos/${repoFullName}/issues/comments/${existing.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ body: renderPrActivityComment([...entries, next], timezone) }),
      });
      return { action: 'updated', commentId: existing.id };
    }

    if (onlyIfPresent) {
      return { action: 'unchanged', commentId: 0 };
    }

    const created = (await githubApi(installationId, `/repos/${repoFullName}/issues/${prNumber}/comments`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ body: renderPrActivityComment([next], timezone) }),
    })) as { id?: number } | null;
    return { action: 'created', commentId: created?.id ?? 0 };
  } catch (error) {
    console.warn(
      `[pr-activity] Could not post ${entry.kind} activity on ${repoFullName}#${prNumber}:`,
      error instanceof Error ? error.message : error,
    );
    return { action: 'failed' };
  }
}
