name: Test With Inputs
on:
  workflow_dispatch:
    inputs:
      env_key:
        description: 'Env var name'
        required: true
        default: 'BUILDD_SIGNING_KEY_TEAM_ID'
      env_value:
        description: 'Env var value'
        required: true
        default: 'd2cb1c29-3f92-4ea1-ba0c-fe8b41ccf3b5'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "key=${{ github.event.inputs.env_key }}"
